### ISSUE TITLE
ARIFA - Taller Interno de Integration

### ISSUE THREAD

**Issue by DiegoPlocheADR** [ubiqua/ARIFA#3]
## JTBD
- Definir un escenario de integracion para Medix App y Arifa DB.

## Context
- ARIFA tiene los datos expuestos en una DB on-premise, SQL Server.
- La DB on-premise esta protegida por un red privada, which requires VPN.
- Mendix, no tiene la capacidad de conexion directa con VPN.
 
## Checklist
- [ ] Definir alternativas para outbound integration.
- [ ] Definir alternativas para inbound integration.

## Importing Data
One of the most important features of Mendix is its ability to integrate with external systems. You can accomplish this integration in several ways, the most important being the ability to integrate with web services like SOAP and REST. Mendix supports XML, JSON, and WSDL and importing is done through mapping which means you do not need to write any code. There are, however, situations in which you need to access the raw data directly. For this, Mendix allows you access to request and response through the HttpRequest and HttpResponse variables. In addition to this, you can use one of the many connectors available in the Mendix Marketplace. There are connectors for AWS, Oracle, SAP, Kafka, OData, and databases (using SQL directly) that allow you to bring data into your Mendix app. If your data is stored in a file, the Mendix Marketplace offers components that allow you to create import functionality for popular file formats like Excel, CSV, PDF, and more. 

**Ejemplo de Integration Scenario**
- Expose: "DB Intermedia con VPN".
- Extract: "Middleware ADR con VPN y SQL".
- Staging: "AWS, Dropbox, Box, Heroku
- Load: Mendix Connector (Kafka, AWS, BOX, SQL Database), Custom Webservices.

## Alternativas, Outbound Integration
- Cliente expone un API REST
- Cliente expone una DB Intermedia que no esté protegida por VPN. (Azure)

## Alternativas, Inbound Integration
- ADR desarrolla y expone un REST API.
- Client exports as CSV to secure location FSTP. => [CSV Connector into Mendix](https://marketplace.mendix.com/link/component/108605).

## Alternativas Middleware
- ADR utiliza un middleware que pueda usar VPN protocol y le escribe/POST a mendix usando ___ 

## Por Ejemplo: "Conexion por medio de Database Connector"
- [ ] [Database Connector](https://marketplace.mendix.com/link/component/2888) para conectarse a una DB SQL. 
- El cliente, expone los datos en una base de datos copia, con credenciales y expuesto con acceso publico. (Sin VPN)

## Documentation
- https://academy.mendix.com/link/modules/313/lectures/2362/4.2-Integration-with-Mendix
- https://www.mendix.com/evaluation-guide/app-capabilities/integration-overview/#integrate-with
- https://marketplace.mendix.com/link/component/2888
- https://www.mendix.com/evaluation-guide/app-lifecycle/app-store/#connectors
- https://marketplace.mendix.com/
- https://docs.mendix.com/apidocs-mxsdk/

**Comment by DiegoPlocheADR** [comment]
Forum with information regarding api creation: https://forum.mendix.com/link/space/app-development/questions/105500

**Comment by DiegoPlocheADR** [comment]
I have compared all inbound and outbound integration possibilites and came to the following conslusion:

1. Inbound would require a lot of effort and time making it the least efficient option. (Involves publishing an API for the consumption of a third party)
2. Consuming a third party web service is and using a marketplace connector to make authentication and managing of the response easier is the most efficient way to achieve the same result. The microflows have the native capability to deserialize JSON and XML. There are also connectors to generate and read .csv which make Mendix the perfect "controlling" app for the integration instead of publishing an api for a third party to consume

**Comment by DiegoPlocheADR** [comment]
Left to determine: How to expose the data from the middleware so that Mendix can access it

Deploying an API in AWS: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-deploy-api.html

**Comment by apicardami** [comment]
## **Diagrama Tentativo de Integracion**
- AWS S3: https://docs.mendix.com/appstore/connectors/aws/amazon-s3/
- AWS RDS: https://docs.mendix.com/appstore/connectors/aws/amazon-rds-database-connector/
- Flujo: {SQL Server + VPN} > Middleware ADR > AWS S3 > Mendix Connector >  Mendix Microflow
